INSERT INTO DPW_DYNAMIC_SCREEN_TAB_DETAILS (
    ID,
    CONTROL_NAME,
    LABEL_NAME,
    TAB_ID,
    MANDATORY,
    DISPLAY,
    EDITABLE,
    GROUP_ID,
    SCREEN_ID,
    SCREEN_COMMENT,
    AUDIT_ACTION,
    ACTION,
    EVENT_TYPE,
    POP_UP_MSG
)
SELECT
    NEXTVAL('DPW_DYNAMIC_SCREEN_TAB_DETAILS_SEQ'),
    'YOUR_CONTROL_NAME',
    'YOUR_LABEL_NAME',
    NULL,
    'N',
    'Y',
    'Y',
    NULL,
    DS.ID,
    NULL,
    NULL,
    'YOUR_ACTION',
    'YOUR_EVENT_TYPE',
    'YOUR_POPUP_MESSAGE'
FROM DPW_DYNAMIC_SCREENS DS
WHERE DS.SCREEN_TYPE = 'EVENT'
AND UPPER(DS.SCREEN_MODE) <> 'CREATE'
AND NOT EXISTS (
    SELECT 1
    FROM DPW_DYNAMIC_SCREEN_TAB_DETAILS DT
    WHERE DT.SCREEN_ID = DS.ID
    AND DT.CONTROL_NAME = 'YOUR_CONTROL_NAME'
);